# Generated by Django 3.0 on 2019-12-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bank',
            field=models.BooleanField(default=False),
        ),
    ]
