# Generated by Django 3.0 on 2019-12-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0002_game_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='bank',
        ),
        migrations.AddField(
            model_name='player',
            name='is_bank',
            field=models.BooleanField(db_column='isBank', default=False),
        ),
    ]
