# Generated by Django 3.0 on 2019-12-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0003_auto_20191218_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_bank',
            field=models.BooleanField(default=False),
        ),
    ]
