# Generated by Django 3.0 on 2019-12-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0004_auto_20191218_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='free_parking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
    ]
