# Generated by Django 3.0 on 2019-12-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0005_auto_20191218_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.CharField(default='royalblue', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.CharField(max_length=9000, null=True),
        ),
    ]
