# Generated by Django 3.0 on 2019-12-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0006_auto_20191220_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
    ]
