# Generated by Django 3.0 on 2019-12-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0007_auto_20191221_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=50)),
                ('to_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('action', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='monopoly.Game')),
            ],
        ),
    ]
