# Generated by Django 3.0 on 2019-12-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0008_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_time',
        ),
    ]
