# Generated by Django 3.0 on 2019-12-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0009_remove_transaction_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
