# Generated by Django 3.0 on 2020-01-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopoly', '0011_auto_20200109_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='sold_properties',
        ),
        migrations.AddField(
            model_name='game',
            name='sold_properties',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
